name: rocket_repository
description: Rocket Repository :)
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  spacex_api:
    path: ../spacex_api

dev_dependencies:
  coverage: ^1.6.3
  mocktail: ^0.3.0
  test: ^1.21.0
